name: devlog_builder
description: A simple script to build the devlog microsite.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  markdown: ^7.2.2
  yaml: ^3.1.2
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  watcher: ^1.1.0
  mustache_template: ^2.0.0
  html: ^0.15.4
  args: ^2.4.2
